import axios from 'axios';
import dotenv from 'dotenv';

dotenv.config();

const TWITCH_API_URL = 'https://api.twitch.tv/helix';

/**
 * Validates the Twitch access token and checks for required scopes
 */
async function validateToken() {
  const clientId = process.env.TWITCH_CLIENT_ID;
  const accessToken = process.env.TWITCH_ACCESS_TOKEN;
  const broadcasterId = process.env.TWITCH_BROADCASTER_ID;

  // Validate environment variables
  if (!clientId || !accessToken || !broadcasterId) {
    console.error('❌ Error: Missing required environment variables');
    console.error('Please ensure the following are set in your .env file:');
    console.error('  - TWITCH_CLIENT_ID');
    console.error('  - TWITCH_ACCESS_TOKEN');
    console.error('  - TWITCH_BROADCASTER_ID');
    return false;
  }

  console.log('🔍 Validating Twitch access token...\n');

  try {
    // Validate the token
    const validateResponse = await axios.get('https://id.twitch.tv/oauth2/validate', {
      headers: {
        'Authorization': `OAuth ${accessToken}`
      }
    });

    const tokenData = validateResponse.data;
    console.log('✅ Token is valid!');
    console.log(`   User ID: ${tokenData.user_id}`);
    console.log(`   Login: ${tokenData.login}`);
    console.log(`   Client ID: ${tokenData.client_id}`);
    console.log(`   Scopes: ${tokenData.scopes.join(', ')}`);
    console.log(`   Expires in: ${tokenData.expires_in} seconds\n`);

    // Check if token belongs to the broadcaster
    if (tokenData.user_id !== broadcasterId) {
      console.error('❌ ERROR: Token mismatch!');
      console.error(`   The access token belongs to user ID: ${tokenData.user_id} (${tokenData.login})`);
      console.error(`   But TWITCH_BROADCASTER_ID is set to: ${broadcasterId}`);
      console.error('\n💡 Solution:');
      console.error('   The access token MUST be generated by the broadcaster account.');
      console.error('   Either:');
      console.error('   1. Generate a new token using the broadcaster account, OR');
      console.error(`   2. Update TWITCH_BROADCASTER_ID to ${tokenData.user_id}\n`);
      return false;
    }

    // Check for required scopes
    const requiredScopes = ['channel:read:redemptions', 'channel:manage:redemptions'];
    const hasRequiredScope = requiredScopes.some(scope => tokenData.scopes.includes(scope));

    if (!hasRequiredScope) {
      console.error('❌ ERROR: Missing required scope!');
      console.error(`   Current scopes: ${tokenData.scopes.join(', ')}`);
      console.error(`   Required scope: channel:read:redemptions OR channel:manage:redemptions`);
      console.error('\n💡 Solution:');
      console.error('   Generate a new access token with one of the required scopes:');
      console.error('   - Using Twitch CLI: twitch token -u -s channel:read:redemptions');
      console.error('   - Or use the OAuth URL in the README with the correct scope\n');
      return false;
    }

    console.log('✅ Token has required scope!');
    console.log('✅ Token belongs to the broadcaster account!');
    console.log('\n✨ All validations passed! You can now run "npm start"\n');
    return true;

  } catch (error) {
    if (error.response && error.response.status === 401) {
      console.error('❌ ERROR: Invalid or expired access token');
      console.error('   The token could not be validated.\n');
      console.error('💡 Solution:');
      console.error('   Generate a new access token with the channel:read:redemptions scope:');
      console.error('   - Using Twitch CLI: twitch token -u -s channel:read:redemptions');
      console.error('   - Or use the OAuth URL in the README\n');
    } else {
      console.error('❌ Error validating token:', error.message);
      if (error.response) {
        console.error('   Status:', error.response.status);
        console.error('   Data:', error.response.data);
      }
    }
    return false;
  }
}

// Run validation
validateToken().then(success => {
  process.exit(success ? 0 : 1);
});
