/**
 * Built-in configuration (auto-generated during build)
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated at: 2025-11-17T11:39:22.402Z
 */

export const BUILTIN_CONFIG = {
  hasBuiltinCredentials: true,
  clientId: "test\"id'with`quotes",
  clientSecret: "test${injection}attempt"
};
