#!/usr/bin/env node

/**
 * Initialization script to ensure config/builtin.js exists
 * This runs after npm install to set up the empty config file
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const configDir = path.join(rootDir, 'config');
const configPath = path.join(configDir, 'builtin.js');

// Only create if it doesn't exist
if (!fs.existsSync(configPath)) {
  // Ensure config directory exists
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  // Create empty builtin config
  const emptyConfig = `/**
 * Built-in configuration (auto-generated during build)
 * This file is automatically created and regenerated by the build process
 * Do not commit this file with embedded credentials
 */

export const BUILTIN_CONFIG = {
  hasBuiltinCredentials: false,
  clientId: null,
  clientSecret: null
};
`;

  fs.writeFileSync(configPath, emptyConfig, 'utf-8');
  console.log('Initialized empty config/builtin.js');
}
