#!/usr/bin/env node

/**
 * Pre-build script to read .secret file and generate built-in config
 * This script runs before electron-builder to embed credentials into the app
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const secretPath = path.join(rootDir, '.secret');
const configOutputPath = path.join(rootDir, 'config', 'builtin.js');

console.log('Pre-build: Reading secret configuration...');

// Check if .secret file exists
if (!fs.existsSync(secretPath)) {
  console.warn('Warning: .secret file not found. Building without embedded credentials.');
  console.warn('Users will need to configure Client ID and Secret manually.');

  // Create empty builtin config
  const emptyConfig = `/**
 * Built-in configuration (auto-generated during build)
 * No credentials were embedded during build
 */

export const BUILTIN_CONFIG = {
  hasBuiltinCredentials: false,
  clientId: null,
  clientSecret: null
};
`;

  // Ensure config directory exists
  const configDir = path.dirname(configOutputPath);
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  fs.writeFileSync(configOutputPath, emptyConfig, 'utf-8');
  console.log('Pre-build: Generated empty builtin config');
  process.exit(0);
}

// Read and parse .secret file
try {
  const secretContent = fs.readFileSync(secretPath, 'utf-8');
  const secrets = {};

  secretContent.split('\n').forEach(line => {
    line = line.trim();
    if (line && !line.startsWith('#')) {
      const [key, ...valueParts] = line.split('=');
      const value = valueParts.join('=').trim();
      secrets[key.trim()] = value;
    }
  });

  // Validate required fields
  if (!secrets.TWITCH_CLIENT_ID || !secrets.TWITCH_CLIENT_SECRET) {
    console.error('Error: .secret file must contain TWITCH_CLIENT_ID and TWITCH_CLIENT_SECRET');
    process.exit(1);
  }

  // Check if values are placeholders
  if (secrets.TWITCH_CLIENT_ID === 'your_client_id_here' ||
      secrets.TWITCH_CLIENT_SECRET === 'your_client_secret_here') {
    console.warn('Warning: .secret file contains placeholder values.');
    console.warn('Please update .secret with your actual credentials.');
    process.exit(1);
  }

  console.log('Pre-build: Found valid credentials');
  console.log(`  - Client ID: ${secrets.TWITCH_CLIENT_ID.substring(0, 8)}...`);
  console.log(`  - Client Secret: ${secrets.TWITCH_CLIENT_SECRET.substring(0, 8)}...`);

  // Generate builtin config file
  const builtinConfig = `/**
 * Built-in configuration (auto-generated during build)
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated at: ${new Date().toISOString()}
 */

export const BUILTIN_CONFIG = {
  hasBuiltinCredentials: true,
  clientId: '${secrets.TWITCH_CLIENT_ID}',
  clientSecret: '${secrets.TWITCH_CLIENT_SECRET}'
};
`;

  // Ensure config directory exists
  const configDir = path.dirname(configOutputPath);
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  fs.writeFileSync(configOutputPath, builtinConfig, 'utf-8');
  console.log('Pre-build: Generated builtin config successfully');
  console.log(`Pre-build: Config written to ${configOutputPath}`);

} catch (error) {
  console.error('Error reading .secret file:', error.message);
  process.exit(1);
}
